### ISSUE TITLE
Sublime crash on double click in 'Build result' window

### ISSUE THREAD

**Issue by rjattrill** [vhyza/exec-in-window#1]
1. Close any existing 'Build result' window
2. Run build (I am building with Perl)
3. Double click on an error message that matches the <code>file_regex</code> for the build system
4. Sublime Text will crash.

A workaround is to tab to a different window and then tab back to the 'Build result' window.   After that the 'Build result' window can be left open and the problem goes away.

**Comment by vhyza** [comment]
Hello,

thanks for the information. Unfortunately I'm not able to replicate it. Please, can you post your `Perl.sublime-build`?

**Comment by rjattrill** [comment]
Hi Vojtech,

Attached is my Perl.sublime-build.

Thank you very much for providing exec_in_window.   I use it all the time
now.

The problem is not just related to Perl I have been able to replicate it
with Ruby.

Steps I have used to replicate on my machine with Ruby:
1.  Ensure that any existing 'Build Results' window has been closed.
2.  Run a script with any error such as test.rb attached.
3.  Click on the line number error in the new 'Build Results' window.

I have made only one change to the default Ruby.sublime-build which has
been to add  "target": "exec_in_window"

Thanks again,

Ross Attrill.

**Comment by vhyza** [comment]
Hello Ross,

I'm sorry, but I don't see any attachments...

**Comment by rjattrill** [comment]
Hi,

I didn't realize that github doesn't support attachments in issues.  (https://github.com/ned14/BEurtle/issues/1.)  The attachments were in the email response and are now available here:

https://docs.google.com/folder/d/0B5wxh47p_EiwN0JQYlhqdV9Tdnc/edit?usp=sharing

I have also posted the sublime-build files to https://gist.github.com/rjattrill/4734576

Thank you vhyza.

**Comment by vhyza** [comment]
Hi @rjattrill,

I'm sorry. I totally forgot about this issue. I'm the worst! Is it still relevant?

**Comment by rjattrill** [comment]
Hi @vhyza.   This issue is not so important to me any more.  While I am still using ST2 I am not using it in the same context as before so am not as reliant on exec-in-window.    OTOH I would however love to see a version of exec-in-window for ST3 as can't find anything quite like it for ST3.

**Comment by vhyza** [comment]
As I wrote earlier in https://github.com/vhyza/exec-in-window/issues/3#issuecomment-22984371, plugin relies on `exec` command which seems to be changed in ST3; so plugin is not compatible. I still don't have a reason to switch to ST3, so I don't expect to support ST3 in near future :(
