### ISSUE TITLE
Problems in Sublime Text 3

### ISSUE THREAD

**Issue by abtris** [vhyza/exec-in-window#2]
I try install via package install and sublime text 3 have this error: 

```
Writing file /Users/prskavecl/zend-ws/swift/examples/test.rb with encoding UTF-8 (atomic)
Unable to find target command: exec_in_window
```

I find some info about porting plugins [here](http://www.sublimetext.com/docs/3/porting_guide.html) but noting about target command.

**Comment by vhyza** [comment]
Thanks for the information. I suppose it has something to do with `exec` command on which plugin relies. I'll try to take a look on it.
