### ISSUE TITLE
No output window in Sublime Text 3

### ISSUE THREAD

**Issue by rjattrill** [vhyza/exec-in-window#3]
- Using ST build 3047
- Install 'Exec in Window' via package control
- Configure build system to include: `"target": "exec_in_window",`
- Add this to preferences: `"show_panel_on_build": false`

Then on building a file, no new buffer is shown - nothing seems to be happening.

**Comment by vhyza** [comment]
Hello,

Sublime Text 3 is not supported right now. `exec in window` relies on `exec` from Sublime Text 2 (https://github.com/vhyza/exec-in-window/blob/master/exec_in_window.py#L10) which is probably changed.

**Comment by rjattrill** [comment]
Thanks Vojtech.   I will stick with ST2 then as I would be lost without
your plugin.   Will you port to ST3 at some point in the future?

Much appreciated,

Ross Attrill.

**Comment by vhyza** [comment]
Probably sometime in the future. But unfortunately, I don't know when. At the latest, when I switch to ST3 :)
